### ISSUE TITLE
Doesn't work on macbook m1 chip

### ISSUE THREAD

**Issue by TheKnightCoder** [textury/arkb#43]
## Steps to replicate
install arkb on Macbook M1 
OS Monterey 
Node v14.18.2

run command `arkb help`

expected:
help output

actual:

```
/Users/r/.nvm/versions/node/v14.18.2/lib/node_modules/arkb/node_modules/blockweave/dist/utils/crypto.js:16
            this.driver = crypto_1.webcrypto.subtle;
                                             ^

TypeError: Cannot read property 'subtle' of undefined
    at new CryptoDriver (/Users/r/.nvm/versions/node/v14.18.2/lib/node_modules/arkb/node_modules/blockweave/dist/utils/crypto.js:16:46)
    at Function.<static_fields_initializer> (/Users/r/.nvm/versions/node/v14.18.2/lib/node_modules/arkb/node_modules/blockweave/dist/blockweave.js:53:21)
    at Object.<anonymous> (/Users/r/.nvm/versions/node/v14.18.2/lib/node_modules/arkb/node_modules/blockweave/dist/blockweave.js:37:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/r/.nvm/versions/node/v14.18.2/lib/node_modules/arkb/bin/utils/utils.js:10:38)
r@rs-MacBook-Pro nft-marriage % arkb     
/Users/r/.nvm/versions/node/v14.18.2/lib/node_modules/arkb/node_modules/blockweave/dist/utils/crypto.js:16
            this.driver = crypto_1.webcrypto.subtle;
                                             ^

TypeError: Cannot read property 'subtle' of undefined
    at new CryptoDriver (/Users/r/.nvm/versions/node/v14.18.2/lib/node_modules/arkb/node_modules/blockweave/dist/utils/crypto.js:16:46)
    at Function.<static_fields_initializer> (/Users/r/.nvm/versions/node/v14.18.2/lib/node_modules/arkb/node_modules/blockweave/dist/blockweave.js:53:21)
    at Object.<anonymous> (/Users/r/.nvm/versions/node/v14.18.2/lib/node_modules/arkb/node_modules/blockweave/dist/blockweave.js:37:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/r/.nvm/versions/node/v14.18.2/lib/node_modules/arkb/bin/utils/utils.js:10:38)
```

**Comment by fuadop** [comment]
Hello @TheKnightCoder ,
This is an issue of nodejs version. Please use nodejs v16.

**Comment by fuadop** [comment]
Check version requirements in package.json file of the repo.

https://github.com/textury/arkb/blob/64c83752e34b0d0b5d0c4024a67e9b91ad3a6f22/package.json#L28-L31
@TheKnightCoder
