### ISSUE TITLE
Possible Syntax error

### ISSUE THREAD

**Issue by BidhanRoy** [textury/arkb#57]
`arkb` commands fail to run. I have tried updating the package, removing node modules then reinstalling dependencies, didn't work for me. I see the following error,

```zsh
% arkb help
/usr/local/lib/node_modules/arkb/bin/commands.js:49
                    const name = tagNames[i]?.toString();
                                             ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/arkb/bin/app.js:9:36)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by fuadop** [comment]
Hey @BidhanRoy ,

What's your nodejs version ?

**Comment by BidhanRoy** [comment]
Updating nodejs seemed to fix it,
